#:kivy 1.10.1
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:include kv/mainscreen.kv
#:include kv/schedulescreen.kv
#:include kv/sleepscreen.kv
#:include kv/appview.kv
#:include kv/mathscreen.kv
#:include kv/RPSscreen.kv


<Manager>:
    MainScreen:
    ScheduleScreen:
    SleepScreen:
    Appview:
    MathScreen:
    RPSScreen: